<a href="https://colab.research.google.com/github/anandababugudipudi/RandomForestClassifier-IRIS-Dataset/blob/main/RandomForestClassifier_IRIS_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Import necessary packages**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

###**Load the IRIS dataset**

In [ ]:
iris_data = load_iris()

###**Seperate Features and Labels**

In [ ]:
X = iris_data.data
y = iris_data.target

print(X.shape)
print(y.shape)

(150, 4)
(150,)


###**Split the data into Train and Test Data**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 122)

###**Build the RFC model**

In [ ]:
model = RandomForestClassifier(n_estimators = 1000, max_features = 'sqrt')

###**Train the model on Training data**

In [ ]:
fitted_model = model.fit(X_train, y_train)

###**Making predictions on Trained model**

In [ ]:
predictions = fitted_model.predict(X_test)

###**Measuring the performance of the model**

In [ ]:
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

[[ 8  0  0]
 [ 0 10  1]
 [ 0  0 11]]
0.9666666666666667
